### ISSUE TITLE
EEPROM Repetier does not writing

### ISSUE THREAD

**Issue by dwonga** [Salandora/OctoPrint-EEPROM-Repetier#7]
Hi!

I checked that my EEPROM repetier, installed into octoprint (raspberry sd-ready version) does not write into the EEPROM. I'm using repetier 0.92.9

Is there any way to check out why or what can I do to make it work?

Thank a lot for your support. It is really appreciated!
David.

**Comment by Salandora** [comment]
Hmm interesting.
Could you please give a step by step instruction on how to produce the problem.
Also please copy your terminal tab after you pushed the save to Eeprom button.

**Comment by NojbyMichal** [comment]
I am having the same problem as dwonga has.

**Comment by Tinchus2009** [comment]
Yes, me too, repetier 0.92. It loads the firmware values, i looks like it save them (at least no error is reported) but the values seems to not have been writen (checked through repetier host)

**Comment by Salandora** [comment]
Quote:
> Could you please give a step by step instruction on how to produce the problem.
Also please copy your terminal tab after you pushed the save to Eeprom button.

Addition:
What electronics do you use, if unknown what printer do you use, is it maybe some special firmware version (rebranded).
Is the firmware self compiled? Check if EEPROM is enabled, provide you Configuration.h files
Is it possible to change the settings through Repetier Host? If no it might be a firmware bug.
Please give as much information as possible, because the only thing this plugin does is check if it is a repetier firmare and then send the commands as specified in the repetier documentation

I do not own a Repetier based printer anymore, so I have no electronics to test it and also I have no Idea if I need to test it on a AVR based or DUE based electronic.

Until someone is giving the requested informations I'm going to close this.
